### ISSUE TITLE
How to generate of blur fields?

### ISSUE THREAD

**Issue by Oktai15** [jannemus/DeepGyro#1]
Hi, @jannemus, great work!

Could you provide code for generation of blur fields?

**Comment by jannemus** [comment]
Thank you! I will add the code for that within the next few days. Stay tuned.

**Comment by Oktai15** [comment]
@jannemus thanks for answer!

Oh, it will be really cool because I want to test your model on my images :)

**Comment by jannemus** [comment]
It took a bit longer than I expected but the code has been added. See the main page for instructions. Thank you for your patience!
